{
 "title": "Team: SLOs",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "period", "label": "SLO period", "query": "1m,5m,10m,30m,1h,30d" },
   {
    "name": "city",
    "query": "label_values(http_server_requests_total{app=\"provider_backend\"}, city)"
   }
  ]
 },
 "panels": [
  {
   "title": "Description",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "SLO description",
     "type": "text",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "#### SLO для API сервера провайдера:\r\n\r\n- 99% запросов получают успешный ответ.\r\n- 99% запросов укладываются в 1 секунду.\r\n\r\n> Этот dashboard создан в образовательных в целях, и поэтому период измерения SLO изменяем.\r\n"
     }
    }
   ]
  },
  { "title": "SLOs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "SLO availability over $period",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100\n* sum(rate(http_server_requests_total{app=\"provider_backend\", code!~\"5..\", city=\"$city\"}[$period]))                                                                                                                                    / sum(rate(http_server_requests_total{app=\"provider_backend\", city=\"$city\"}[$period]))"
    }
   ]
  },
  {
   "title": "SLO latency over $period",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100\n  * sum(rate(http_server_request_duration_seconds_bucket{app=\"provider_backend\", le=\"1.0\", city=\"$city\"}[$period]))\n  / sum(rate(http_server_request_duration_seconds_count{app=\"provider_backend\", city=\"$city\"}[$period]))"
    }
   ]
  },
  { "title": "History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "SLO availability over $period",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100                                                                                                                                                                                                                 * sum(rate(http_server_requests_total{app=\"provider_backend\", code!~\"5..\", city=\"$city\"}[$period]))                                                                                                                                    / sum(rate(http_server_requests_total{app=\"provider_backend\", city=\"$city\"}[$period]))",
     "legendFormat": "{{ slo availability }}"
    }
   ]
  },
  {
   "title": "SLO: latency over $period",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100\n  * sum(rate(http_server_request_duration_seconds_bucket{app=\"provider_backend\", le=\"1.0\", city=\"$city\"}[$period]))\n  / sum(rate(http_server_request_duration_seconds_count{app=\"provider_backend\", city=\"$city\"}[$period]))",
     "legendFormat": "{{ slo latency }}"
    }
   ]
  },
  {
   "title": "Remaining availability budget over $period",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none", "label": "requests" }
   ],
   "targets": [
    {
     "expr": "(\n  # number of allowed \"bad\" requests\n  sum(increase(http_server_requests_total{app=\"provider_backend\", city=\"$city\"}[$period])) # overall number of requests\n  *\n  (1 - 0.99) # our target, i.e. 100 - 99 %\n)\n-\nsum(\n  increase(http_server_requests_total{app=\"provider_backend\", code=~\"5..\", city=\"$city\"}[$period])  # number of failed requests\n  or up * 0 # account for possible missing failed requests\n)\n",
     "legendFormat": "remaining budget"
    }
   ]
  },
  {
   "title": "Remaining latency budget over $period",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "requests" }
   ],
   "targets": [
    {
     "expr": "( # number of allowed \"bad\" requests\n  sum(increase(http_server_request_duration_seconds_count{app=\"provider_backend\", city=\"$city\"}[$period])) # overall number of requests\n  *\n  (1 - 0.99) # our target, i.e. 100 - 99 %\n)\n-\n( # here we compute amount of requests slower than one second\n  sum(increase(http_server_request_duration_seconds_count{app=\"provider_backend\", city=\"$city\"}[$period]))\n  -\n  sum(increase(http_server_request_duration_seconds_bucket{app=\"provider_backend\", le=\"1.0\", city=\"$city\"}[$period]))\n)",
     "legendFormat": "remaining budget"
    }
   ]
  }
 ]
}