apiVersion: v1
kind: Service
metadata:
  {{- if or .Values.annotations .Values.service.annotations }}
  annotations:
    {{- if .Values.annotations }}
    {{- range $key, $val := .Values.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
    {{- end }}
    {{- if .Values.service.annotations }}
    {{- range $key, $val := .Values.service.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
    {{- end }}
  {{- end }}
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: app
  name: {{ .Release.Name }}
spec:
  ports:
  - name: http
    port: {{ .Values.service.external_port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    component: app
  sessionAffinity: None
  type: ClusterIP
